---
- name: Build and Push Docker image
  remote_user: ansible
  become: true
  hosts: docker_hosts

  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: kapilproject2
        tag: latest
        source: build
        build:
          pull: no
          path: /home/jagenthome/workspace/jenkinscicd
          dockerfile: Dockerfile

    - name: Login into Docker Hub
      docker_login:
        username: kapcareer@gmail.com
        password: pass12345

    - name: Push Docker image to Docker Hub
      docker_image:
        name: helloworld1977/helloworld
        tag: kapilproject2
        source: image

    - name: Log out from Docker Hub
      command: docker logout
