- name: Build Docker image
  remote_user: ansible
  become: true
  hosts: docker_hosts

  vars:
    ansible_user: ansible  # Specify the SSH user
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: kapilproject2:latest
        source: build
        build:
          pull: no
          path: /home/jagenthome/workspace/JenkinsCICD
          dockerfile: Dockerfile

