---
- name: Build Docker image
  remote_user: ansible
  become: true
  hosts: docker_hosts

  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: kapilproject2:latest
        source: build
        build:
          pull: no
          path: /home/jagenthome/workspace/jenkinscicd
          dockerfile: Dockerfile

    - name: Login into the docker hub
      docker_image:
        username: kapcareer@gmail.com
        password: pass12345
    - name: Build Docker image from Dockerfile
      docker_image:
        name: helloworld1977/helloworld
        tag : kapilproject2:latest
        source: image
        

    - name: log out from the docker
      command: docker logout
        
